# -*- coding: utf-8 -*-
"""NewCode.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZGyXKpIYhoKsTj7m05qtntvcck6vt5Jz
"""

import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt

# Title of the app
st.title("Mental Health Data Visualization by State")

# File uploader for CSV
uploaded_file = st.file_uploader("Upload your CSV file", type=["csv"])

if uploaded_file is not None:
    # Read the CSV file
    data = pd.read_csv(uploaded_file)

    # Show data preview
    st.write("### Data Preview")
    st.dataframe(data.head())

    # Ensure expected columns are present
    required_columns = ["State", "Year", "Percentage With Mental Distress", "Total Number of Survey Respondents"]
    if all(col in data.columns for col in required_columns):
        # Filter options for state and year
        states = data["State"].unique()
        selected_state = st.selectbox("Select a State", states)
        years = sorted(data["Year"].unique())
        selected_year = st.selectbox("Select a Year", years)

        # Filter data based on selections
        filtered_data = data[(data["State"] == selected_state) & (data["Year"] == selected_year)]

        st.write(f"### Data for {selected_state} in {selected_year}")
        st.dataframe(filtered_data)

        # Dropdown for selecting columns for visualization
        y_column = st.selectbox(
            "Select Y-axis column",
            ["Percentage With Mental Distress", "Total Number of Survey Respondents"]
        )

        graph_type = st.selectbox(
            "Select Graph Type",
            ["Line", "Scatter", "Bar"]
        )

        # Plot button
        if st.button("Plot Graph"):
            fig, ax = plt.subplots()

            if graph_type == "Line":
                ax.plot(filtered_data["Year"], filtered_data[y_column], marker='o')
                ax.set_title(f"{y_column} over Years in {selected_state}")

            elif graph_type == "Scatter":
                ax.scatter(filtered_data["Year"], filtered_data[y_column])
                ax.set_title(f"{y_column} vs Year in {selected_state}")

            elif graph_type == "Bar":
                ax.bar(filtered_data["Year"], filtered_data[y_column])
                ax.set_title(f"{y_column} by Year in {selected_state}")

            ax.set_xlabel("Year")
            ax.set_ylabel(y_column)
            st.pyplot(fig)
    else:
        st.error(f"Uploaded file is missing one or more required columns: {required_columns}")
else:
    st.info("Please upload a CSV file to get started.")